export const orgs = [
  "Aquent",
  "Babcock & Jenkins",
  "BASIC",
  "The Beauty Shop",
  "Centric Park",
  "ConnectiveDX",
  "creative FEW",
  "Daylight",
  "DXM",
  "Emerge Interactive",
  "EOLA Amity Hills",
  "EY Design Studio",
  "Futura Collective",
  "Greystar",
  "Hanlon Brown",
  "ILTS",
  "Instrument",
  "Mindjet",
  "MIT",
  "Monumental",
  "Opus Creative",
  "The Other Agency",
  "Periscope Creative",
  "Procter & Gamble",
  "Razorfish",
  "Rose CDC",
  "Shirtspace",
  "StudioLabs",
  "Vitamin T",
  "Webtrends",
  "Yum!",
];
